-- changing dtype of various columns

alter table Superstore
alter column Sales float

alter table Superstore
alter column quantity int

alter table Superstore
alter column profit float

alter table Superstore
alter column discount float


-- rounding columns to two decimal places

update superstore
set Sales = ROUND(sales, 2)

update superstore
set profit = ROUND(profit, 2)

select *
from superstore


--1. total sales, total profit and profit margin 

select round(sum(sales),0) as total_sales, round(sum(profit),0) as total_profit, round((sum(profit)/sum(sales)*100),2) as profit_margin_in_percent
from superstore

--over the period under review the company made total sales of 2,3 mln in revenue, 0,286mln in sales which stands for 12,5% of profit margin


--2. profitability per segment

select segment, round(sum(profit),2) as sum_of_profit, (sum(profit)*1.0/(select sum(profit) from superstore)) as percentage_of_total_profit
from superstore
group by segment
order by sum_of_profit desc;

--most profitable segment of the company is "consumer" which generates ~ 46% of total profit and the least is "home office" with its ~ 21 % of total generated profit


--3. profitability per state

--number of states in total
select count(distinct state) as total_number_of_states
from Superstore

--4. deficit states

select state, round(sum(profit),2) as deficit
from superstore
group by state
having round(sum(profit),2) < 0
order by deficit asc;



--5. total sales and total profit per category and subcategory

select category, [sub-category],round(sum(sales),0) as total_sales_per_sub_category, round(sum(profit),0) as total_profit_per_sub_category 
from superstore
group by category, [sub-category] 
order by category, total_profit_per_sub_category desc;


--6. top 15 most profitable cities

select top 15 city, sum(profit) as sum_of_profit
from superstore
group by city
order by sum_of_profit desc;

--7. average profitability per category

select category, (sum(profit)/sum(sales)*100) as avg_profitability
from superstore
group by category
order by avg_profitability desc;

--8. average profitability per sub-category

select [sub-category], (sum(profit)/sum(sales)*100) as avg_profitability
from superstore
group by [sub-category]
having sum(profit)/sum(sales)*100 > 0
order by avg_profitability desc;

--9. what subcategory has the biggest turnover? what percentage of a total turnover are they?

select [sub-category], sum(quantity) as total_quantity_per_subcategory, (sum(quantity)*1.0/(select sum(quantity) from superstore)) as percentage_of_total_turnover
from superstore
group by [sub-category]
order by percentage_of_total_turnover desc;

--10. Top 5 biggest volume-generating subcategories

select TOP 5 [sub-category], sum(sales) as volume_per_subcategory
from superstore
group by [sub-category]
order by [sub-category] desc;


--11. Below query results in running percentage of total profits for states that are profitable. Only profits that were generated by profitable states are counted

--That being said, two most profitable states generates ~ 40% of total profit made by profitable states and top 5 states generates ~ 59% of total profits made by profitable states

select 
 state
,profit_per_state
,profit_per_state/total_profit as percentage_of_total_profit
,sum(profit_per_state/total_profit) over (order by profit_per_state desc) as running_percentage
from	(select 
		state
		,sum(profit) as profit_per_state
		,(select sum(profit) from superstore where state not in( 
			select state
			from Superstore
			group by state
			having sum(profit) < 0)
		) as total_profit
		from Superstore
		group by state
		having state not in
			(select state
			from Superstore
			group by state
			having sum(profit) < 0
			)
		) as temp


-- 12. What products are being shipped first class and second class? And how many?

select [ship mode]
,[sub-category]
,sum(cast(quantity as float)) as total_quantity
,ROW_NUMBER() over (partition by [ship mode] order by [ship mode]) as 'row number of each ship mode'
from superstore_desc as s1
INNER JOIN superstore_num as s2
ON s1.ind = s2.ind
group by [ship mode], [sub-category]
having [ship mode] IN ('Second Class', 'First Class')
order by [ship mode], total_quantity desc;


	-- number of sub-categories in total
	select count(distinct [sub-category]) as total_number_of_subcategories
	from superstore_desc

-- turns out that all sub-category products are shipped both first class and second class.


--13. Basic numerical data statistics

SELECT state
,round(AVG(cast (sales as float)),2) AS AvgSales 
,MAX(cast (Quantity as int)) AS MaxQuantity
,round(SUM(cast (Profit as float)),2) AS TotalProfit
FROM superstore_desc s1
INNER JOIN superstore_num s2
ON s1.ind = s2.ind
GROUP BY state
order by state asc;


--14. Cummulative sum of sales per state

select state
,[sub-category]
,round(sales,2) as sales
,sum(cast(sales as float)) over (partition by state order by sales rows between unbounded preceding and current row) as cumsum
from superstore_desc as s1
INNER JOIN superstore_num as s2
ON s1.ind = s2.ind


--15. Remaking query no. 11 into common table expression based query

with cte as
(
select 
		state
		,sum(profit) as profit_per_state
		,(select sum(profit) from superstore where state not in( 
			select state
			from Superstore
			group by state
			having sum(profit) < 0)
		) as total_profit
		from Superstore
		group by state
		having state not in
			(select state
			from Superstore
			group by state
			having sum(profit) < 0
			)
)
select 
 state
,profit_per_state
,profit_per_state/total_profit as percentage_of_total_profit
,sum(profit_per_state/total_profit) over (order by profit_per_state desc) as running_percentage
from cte	












select *
from Superstore